### ISSUE TITLE
PT作弊共享是什么意思？

### ISSUE THREAD

**Issue by ixiusama** [chdproxy/ptproxy#1]
RT

**Comment by chdproxy** [comment]
PT是Private tracker的简称，基于BitTorrent网络原理，提供传输盗版资源（中国大陆以盗版电影为主）的用户信息交换平台。基于PT的网站需要用户下载资源完毕保持上传，且上传流量/下载流量需要保持一定的比率以上，才能继续保有该盗版站账号，否则删除账号。由于迅雷客户端不能正确提交用户上传下载流量数据信息，不能正确统计，被各站屏蔽了。由于PT网站是使用BitTorrent网络交换用户盗版资源，只需要知晓上传者IP和端口号，就能正常下载。所以基于这个原理，只需要有盗版站账户的用户，从服务器取得其他用户的IP和端口号，提供给其他支持BitTorrent下载的软件就可以方便没有账户的人下载盗版资源。

**Comment by ixiusama** [comment]
那这个应该如何使用呢？
